from eve.utils import config
from eve_sqlalchemy.decorators import registerSchema
from tables import Character, Powerup

ID_FIELD = 'id'
config.ID_FIELD = ID_FIELD
RESOURCE_METHODS = ['GET']

# Need to be called *after* setting config.ID_FIELD
registerSchema('character')(Character)
registerSchema('powerup')(Powerup)

SQLALCHEMY_DATABASE_URI = 'postgresql://nintendo_user:MarioLuigi24@dev.jitsejan.com:5433/nintendo'

# The following two lines will output the SQL statements executed by SQLAlchemy.
# Useful while debugging and in development. Turned off by default
# --------
SQLALCHEMY_ECHO = True
SQLALCHEMY_RECORD_QUERIES = True

DEBUG = True

# The default schema is generated by the decorator
DOMAIN = {
    'character': Character._eve_schema['character'],
    'powerup': Powerup._eve_schema['powerup'],
}